id: I4163DE15
legacy_id: P000812
ocr_import_info:
  bdrc_scan_id: W3CN18534
  source: bdrc
  ocr_info:
    timestamp: '2021-04-05T10:27:03'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T12:20:31.642823+00:00'
last_modified: 2022-09-03 20:20:50.214619
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN18534
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN18534
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་ཐོར་བུ། བློ་ལྡན་ཤེས་རབ།
  author: རྔོག་བློ་ལྡན་ཤེས་རབ།
statistics:
  ocr_word_mean_confidence_index: 0.7423918148774176
  ocr_word_median_confidence_index: 0.8
quality: null
bases:
  I3CN21192:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN21192
      total_pages: 526
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN21192.txt
    statistics:
      ocr_word_median_confidence_index: 0.8
      ocr_word_mean_confidence_index: 0.7423918148774176
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
