id: P000812
initial_creation_type: ocr
created_at: 5/04/2021
last_modified_at: 2021-12-17 10:11:58.107680
source_metadata:
  id: bdr:W3CN18534
  title: གསུང་ཐོར་བུ། བློ་ལྡན་ཤེས་རབ།
  volumes: {}
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
